service: serverless-crud-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  createOrder:
    handler: handler.create
    events:
      - http:
          path: orders
          method: post
          cors: true

  getOrder:
    handler: handler.get
    events:
      - http:
          path: orders/{id}
          method: get
          cors: true

  updateOrder:
    handler: handler.update
    events:
      - http:
          path: orders/{id}
          method: put
          cors: true

  deleteOrder:
    handler: handler.remove
    events:
      - http:
          path: orders/{id}
          method: delete
          cors: true

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orders-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

