service: serverless-crud-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  createItem:
    handler: handler.create
    events:
      - http:
          path: items
          method: post
          cors: true

  getItem:
    handler: handler.get
    events:
      - http:
          path: items/{id}
          method: get
          cors: true

  updateItem:
    handler: handler.update
    events:
      - http:
          path: items/{id}
          method: put
          cors: true

  deleteItem:
    handler: handler.remove
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: items
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

