name: Deploy Serverless API

on:
  push:
    branches:
      - main
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Install Dependencies
        run: npm install

      - name: Deploy to AWS with Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "Deploying to PROD stage..."
            serverless deploy --stage prod
          else
            echo "Deploying to DEV stage..."
            serverless deploy --stage dev
	  fi

